project_root/
├─ data/
│  ├─ raw/               # Store original downloaded data files here
│  ├─ processed/         # Store cleaned and feature-engineered datasets here
├─ src/
│  ├─ data_collection/   # Scripts related to downloading or accessing Airbnb data
│  ├─ data_cleaning/     # Scripts for cleaning and preprocessing the raw data
│  ├─ feature_engineering/ # Scripts for creating new features, transformations
│  ├─ visualization/     # Scripts/notebooks for creating plots and interactive visuals
│  ├─ modeling/          # Scripts for training, evaluating, and saving models
│  ├─ utils/             # Helper functions that can be shared across modules
├─ tests/
│  ├─ test_data_cleaning/   # Test scripts ensuring cleaning steps are correct
│  ├─ test_feature_engineering/ # Tests for validating feature transformations
│  ├─ test_modeling/         # Tests ensuring model trains and predicts correctly
│  ├─ test_visualization/    # Optional tests for checking if visualization scripts run without error
├─ notebooks/
│  ├─ eda.ipynb          # Exploratory data analysis notebook
│  ├─ modeling_experiments.ipynb # Experimentation with different models
│  ├─ visualization_experiments.ipynb # Experimentation with plots/interactive visuals
├─ environment.yml        # Conda environment file or requirements.txt for Python packages
├─ Makefile               # Make commands to set up environment, run pipeline, run tests
├─ README.md              # Project overview, setup instructions, methodology, results, contribution guidelines
├─ .github/
│  └─ workflows/
│     └─ test.yml         # GitHub Actions workflow to run tests automatically
└─ figures/
   ├─ eda_plots/          # Static figures generated by EDA scripts or notebooks
   ├─ model_evaluation/   # Plots related to model performance
